### PR TITLE
Functions for folders and types

### PR DESCRIPTION
**Pull request by agn-fj**
Adjusted Retrieve() so that non-* items can be exported and/or fetched.

### CODE REVIEW

**Comment by agn-fj** [comment]
Adding support for the following 4 non-wildcard types that the CLI currently attempts to export/fetch:

- Dashboard
- Document
- EmailTemplate
- Report

Good:
 - Works!
 - Less confusion/disappointment over missing EmailTemplates (#149)
 - The CLI may offer increased value for users looking to back up their org's metadata more fully (me)

Less Good:
- Hardcoding the folder names into a new function (GetFolderTypeName) in metadata.go didn't feel great  
- Neither does calling the api repeatedly - once for each folder

Details on * vs. non-* types: http://www.salesforce.com/us/developer/docs/api_meta/Content/meta_types_list.htm

**Comment by dcarroll** [comment]
I'm curious, should the folder name just be the type + "Folder"?  

Could definitely see about batching up the calls to each folder.  I haven't dug into the details around that.  Also, we have a lot a new REST MD calls that we can look to and see if there are any equivalents that might allow for more optimization.

**Comment by agn-fj** [comment]
They almost match up - but that would be too easy!

The outlier in this group is the "EmailTemplate" type which has a folder name of "Email"

This SOQL may illustrate it more clearly when you run it:
- SELECT Name,Type FROM Folder

I'll check out the REST calls and see if I can be more economical -

**Comment by dcarroll** [comment]
I'd rather code for the exceptions.

Dave Carroll
Ra
On Mar 31, 2015, at 10:02 AM, agn-fj <notifications@github.com> wrote:

They almost match up - but that would be too easy!

The outlier in this group is the "EmailTemplate" type which has a folder
name of "Email"

This SOQL may illustrate it more clearly when you run it:

   - SELECT Name,Type FROM Folder

I'll check out the REST calls and see if I can be more economical -

—
Reply to this email directly or view it on GitHub
<https://github.com/heroku/force/pull/162#issuecomment-88172203>.

**Comment by cwarden** [comment]
This is a nice feature, but it would be even better if it fetched the folder metadata.  It looks like [readMetadata](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_readMetadata.htm) needs to be used to get the folder metadata.  See http://salesforce.stackexchange.com/a/49956/240

The folder metadata contains the sharing configuration for the folder.

**Comment by dcarroll** [comment]
As an awkward and unfortunate by-product of reducing the git objects in this repo from 145 MB to 6 MB (due to lot's of binaries previously committed to this repo) you will need to rebase your fork to master and resubmit this pull request.

**Pull request closed without merging**
