### PR TITLE
Add Ability to Deploy Queues by Path

### PR DESCRIPTION
**Pull request by cwarden**
Add ability to deploy Queues by path using `force push`.

### CODE REVIEW

**Comment by dcarroll** [comment]
As an awkward and unfortunate by-product of reducing the git objects in this repo from 145 MB to 6 MB (due to lot's of binaries previously committed to this repo) you will need to rebase your fork to master and resubmit this pull request.

**Comment by dcarroll** [comment]
I'm going to see if I can get the changes in with a pull request of my own, my mistake so I should try to solve.

**Comment by cwarden** [comment]
I rebased on the the new master.

**Comment by dcarroll** [comment]
Did it clean up the commit list for the pull?


On Tue, Jan 12, 2016 at 1:12 PM, Christian G. Warden <
notifications@github.com> wrote:

> I rebased on the the new master.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/pull/236#issuecomment-171055955>.
>



-- 
Thanks,
Dave

**Comment by cwarden** [comment]
The steps to rebase are:
 * check out the pull request branch, `deploy-queues` in this case
 * Use `git rebase --interactive` and select only the commit(s) from your branch
 * Force push your branch to your fork on github, e.g. `git push --force github`

rebase

**Pull request merged**
