### PR TITLE
Trace and Log Enhacement

### PR DESCRIPTION
**Pull request by sebastianclaros**
Thank for sharing this application. We are doing performance test automation and we need to manage trace and logs. 
Basically I added the possibility of delete TraceFlags with criterias and create new TraceFlags custom.
On the other hand I added debug log parsing in order to extract DML, SOQL, and APEX CODE information. 
For example for start debugging a user X here is the bash command

#!/bin/bash
# $1 username for login
# $2 password for login
# $3 debug user

force login -u=$1 -p=$2
force trace delete csv TracedEntity.Id:$3
force log delete LogUserId:$3
force trace start Log:DML Log:SOQL Log:CODE Log:HEAP TracedEntityId:$3

And to analyse logs after a set of actions that the user $3 has done.

#!/bin/bash
# $1 username for login
# $2 password for login
# $3 debug user
force log download LogUserId:$3
# For each Log
for filename in *.log; do
	#Toma el id del Log
	fullname=$(basename $filename)
	basename="${fullname%.*}"	
	force log parse csv-noheader ./$filename  EventType:ROOT >> "./"$basename"_measures.csv"
# SOQL
	force log parse csv-noheader ./$filename  EventType:SOQL > "./$4/"$basename"_soql.csv"
# DML
	force log parse csv-noheader ./$filename  EventType:DML > "./$4/"$basename"_dml.csv"
# HEAP
	force log parse csv-noheader ./$filename  EventType:HEAP > "./$4/"$basename"_heap.csv"
# CODE
	force log parse csv-noheader ./$filename  EventType:CODE > "./$4/"$basename"_code.csv"
	mv ./$filename ./$4/$filename
done

I hope this can be useful and please give me your feedback, is my first time that I participate in a gitbuh project....

### CODE REVIEW

**Comment by sebastianclaros** [comment]
Hi,

I added a new command rest to execute custom rest api services.

Best Regards,

Sebastian

**Comment by dcarroll** [comment]
I'm not convinced that this is the right approach.  Instead, the trace command should function similar to what is provided in the UI and should used flagged arguments.

`force trace start [--startdate] [--stopdate] [--debuglevel=named_level] --entity=UserId | ApexClassId | ApexTriggerId`
To create a named debug level:
`
force trace:debuglevel --name=debug_level_name <field:level>. <field:level>...
`

An example:
Create or update the debug level named my_level
`force trace:debuglevel --name=my_level ApexCode:INFO Callout:INFO`

Start a new trace log
`force trace start --debuglevel=my_level --entity= 01pB0000000MUMaIAO`

**Comment by sebastianclaros** [comment]
Hi Dave,

Yes, I agree, unfortunately the api is not like the UI (
https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/tooling_api_objects_traceflag.htm).
I will add the start and stop date (expiration),  I remembered that the
start date was throwing an error but may be because at the begging it was
with the api 34.

I will pull request with the changes.

Thanks,

Best Regards,

Sebastian

[image: photo]Sebastian Claros
Director of Engineering, Fielo

Phone: +54 (11) 4742 9900  <+54+(11)+4742+9900>
Mobile: +54 (911) 66553981 <+54+(911)+66553981>
Email: sebastian.claros@fielo.com  <sebastian.claros@fielo.com>
Website: www.fielo.com
Skype: sebasclaros
Address: 25 de Mayo 424, San Isidro, Argentina

**Comment by dcarroll** [comment]
As an awkward and unfortunate by-product of reducing the git objects in this repo from 145 MB to 6 MB (due to lot's of binaries previously committed to this repo) you will need to rebase your fork to master and resubmit this pull request.

**Pull request closed without merging**
