### PR TITLE
Deploy Flows

### PR DESCRIPTION
**Pull request by cwarden**
Add support for deploying Process Builder Flows.

### CODE REVIEW

**Comment by dcarroll** [comment]
Should I give you committer rights?

Dave Carroll

**Comment by cwarden** [comment]
If you'd like to, sure.  I'd be happy to help you review and merge
changes.

**Comment by dcarroll** [comment]
Arg, I can't add you.  Need to be a member of the Heroku organization.

**Comment by diligent176** [comment]
Anything that can help move this project forward quicker would be a huge win ;-)
I'm trying to learn Golang specifically so I can help contribute to forceCLI improvements.

Speaking of Heroku, it would be really good to remove forceCLI's dependency on Heroku.
My company is planning to adopt the CLI into an automated SFDC build pipeline.  But if there's a hard dependency on Heroku, that could be a real deal breaker.

(We currently have a substantial amount of build automation around Force ANT migration tool.)

**Comment by cwarden** [comment]
@diligent176, my change to remove the dependency on the Heroku app and add automatic refreshing of OAuth tokens could use some more testing: f5c35082c7d9486f3e89ebf04c4ca565488ff8bc

**Comment by orospakr** [comment]
One issue we've run into (with both the ant tool and heroku/force) is that subsequent re-deploys fail because Salesforce' immutable versioning regime for Process Builder (a laudable yet in my opinion misguided attempt to apply developer best practices into their platform).

In our own branch (scary hacks!) of the ant deploy tool, we implemented code that automatically increments the flow version numbers, but this is arguably a bit inelegant.  Another solution may be just to skip deploying flow versions that already exist in the target environment, or perhaps to do a compare.

What do you folks think?

**Comment by dcarroll** [comment]
How does it fail?  IE what kind of error message is returned.  I thought that flows just could only have 1 version that was active.  I'll admit to never having tried it myself. Not sure exactly what you mean by compare. 

Is this a situation where you are pulling a bunch of metadata and modifying a couple pieces of it and then redeploying the stuff that wasn't changed with the changed stuff?

**Comment by diligent176** [comment]
I think I know what he's saying.  We've had to work around this in our build automation.
_Error: The version of the flow you're updating is active and can't be overwritten_

This is because we've commited a specific version of a flow to source control, and it has been deployed one time already to the target org.  Deploying it again results in the error message above from force metadata API.

So in our workflow (SFDC ANT migration tool), we produce a second metadata package without the flows and deploy that instead.  The error is from force API - not really a forceCLI issue in my opinion.

**Comment by dcarroll** [comment]
Not sure there is anything different that can be done other than the idea
of pre-processing the flow metadata to see if anything has changed
(compare) and exclude if not, rename the metadata file if so.  In any case,
I did not see where you can control activation through any API. This is
definitely a corner case that I'd like to escalate.

Dave Carroll

On Apr 12, 2016, at 3:58 PM, Jason Bellis <notifications@github.com> wrote:

I think I know what he's saying. We've had to work around this in our build
automation.
*Error: The version of the flow you're updating is active and can't be
overwritten*

This is because we've commited a specific version of a flow to source
control, and it has been deployed one time already to the target org.
Deploying it again results in the error message above from force metadata
API.

So in our workflow (SFDC ANT migration tool), we produce a second metadata
package without the flows and deploy that instead. The error is from force
API - not really a forceCLI issue in my opinion.

—
You are receiving this because you modified the open/close state.
Reply to this email directly or view it on GitHub
<https://github.com/heroku/force/pull/271#issuecomment-209138166>

**Pull request merged**
