### PR TITLE
Support for `force bulk query retrieve` to retrieve multiple result files. Fixes #140

### LINKED ISSUE #140: `force bulk query retrieve [job id] [batch id]` only returns the first result file, and not any subsequent files
If you do a large enough Bulk API Query, Salesforce chunks this up into multiple result files. The `force bulk query retrieve [job id] [batch id]` command appears to only be retrieving one of these files.

### PR DESCRIPTION
**Pull request by mickle00**
As large bulk queries can result in Salesforce delivering multiple result files, it's necessary to download all of them, and not just the first.

This code checks for presence of multiple result files. If there is only one result file, there is no change to the current behavior. If there are multiple, it gets them one-by-one, concatenated together, separated by a line "ResultId: $RESULT_ID".

As the current behavior simply prints to stdout (and does not create csv files on the local filesystem), I'm keeping this functionality as is, and leaving it up to the caller to do what they with the streamed data.

For example, to break this into separate files (on *nix) can use:
`force bulk query retrieve $JOB_ID $BATCH_ID | split -p "ResultId: .+" - Output_`

This is my first time writing Go, so let me know if there are any improvements to the code. I tried to keep the styling inline with all the other code.

### CODE REVIEW

**Comment by harmoney-danielb** [comment]
There is a StackExchange question related to this functionality - [Force.com CLI bulk query returns nothing](http://salesforce.stackexchange.com/q/82772/102). It appears that if there is only a single AsyncApiQueryResult the data isn't coming back.

At least that appears to be the case for the asker and my attempts to reproduce it.

**Comment by FishOfPrey** [comment]
There is a StackExchange question related to this functionality - [Force.com CLI bulk query returns nothing](http://salesforce.stackexchange.com/q/82772/102).

 It appears that if there is only a single AsyncApiQueryResult Id in the batch results the data isn't coming back.

At least that appears to be the case for the asker and my attempts to reproduce it.

**Comment by mickle00** [comment]
Yikes! Good catch @FishOfPrey. It looks like a last minute naming convention change I made to the file before introducing the pull request introduced the bug. I thought I had ran a final compile & re-test, but it appears the final changes never got compiled, and unbeknownst to me, the version I've been running locally was compiled just before this naming convention change so has been functioning as expected since. 

I've attached a new pull request #188 which hopefully gets merged in soon, as it fixes the issue. 

Thanks for bringing this to my attention, and sorry for introducing the bug! This is the first Go I've written, and I'm not sure how I missed the final compile before issuing the pull request!

**Comment by FishOfPrey** [comment]
@mickle00  No problem. Thanks for taking the time to extend the functionality.

**Pull request merged**
