### PR TITLE
Deploy S-Controls

### PR DESCRIPTION
**Pull request by cwarden**
Add support for deploying S-Controls by path.

### CODE REVIEW

**Comment by dcarroll** [comment]
SControls!!!! Are you still using those??  Now I really wish this CLI had a plugable architecture!  I'll do this if your boss sends me one a six pack from Alberta Brewing company!

**Comment by cwarden** [comment]
Yep, still have some s-controls in use in this application.  The svn repo is almost eight years old.

```
commit ef53388770ab8f4a3052ee291bccfb86805ea805
Author:     cwarden <cwarden@8f9973a1-582a-0410-93ec-f10688ae947f>
AuthorDate: Wed Feb 6 14:07:31 2008
Commit:     cwarden <cwarden@8f9973a1-582a-0410-93ec-f10688ae947f>
CommitDate: Wed Feb 6 14:07:31 2008

    import eclipse workspace for new salesforce development
```

@jimpdx isn't my boss anymore, but I'll see if I can bring along some Alberta Brewing next time I travel down to the bay area.  Now you've got me craving a Moebius Vanilla IPA.

**Comment by jimpdx** [comment]
@dcarroll shoot me an email with your address and I can send you a selection :) No reason that @metadaddy should have all the fun!

**Comment by dcarroll** [comment]
Haha, my comment was totally in jest!

On Mon, Jan 18, 2016 at 8:51 AM, Jim Thompson <notifications@github.com>
wrote:

> @dcarroll <https://github.com/dcarroll> shoot me an email with your
> address and I can send you a selection :) No reason that @metadaddy
> <https://github.com/metadaddy> should have all the fun!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/pull/240#issuecomment-172585449>.
>



-- 
Thanks,
Dave

**Pull request merged**
